CREATE TABLE CUSTOMERS(
   ID   INT              NOT NULL,
   FIRST_NAME VARCHAR (40)     NOT NULL,
   LAST_NAME VARCHAR (40)     NOT NULL,
   AGE  INT              NOT NULL,
   ADDRESS  VARCHAR (100) ,
   SALARY   DECIMAL (18, 2),
   PRIMARY KEY (ID)
);

--//@UNDO

DROP TABLE CUSTOMERS;