CREATE TABLE USER(
   ID INT   NOT NULL AUTO_INCREMENT,
   PASSWORD VARCHAR(40)    NOT NULL,
   NAME VARCHAR(40)        NOT NULL,
   EMAIL_ADDRESS VARCHAR(100)     NOT NULL,
   PHONE_NUMBER VARCHAR(15),
   COUNTRY VARCHAR (50) NOT NULL,
   GENDER VARCHAR(10) NOT NULL,
   AGE INT NOT NULL,
   PRIMARY KEY (ID)
);

--//@UNDO

DROP TABLE USER;