CREATE TABLE USER(
   USER_ID VARCHAR (20) NOT NULL,
   PASSWORD VARCHAR (40)  NOT NULL,
   NAME VARCHAR (40)     NOT NULL,
   EMAIL_ADDR VARCHAR (40)     NOT NULL,
   PHONE_NUM VARCHAR (15),
   COUNTRY VARCHAR (15)     NOT NULL,
   GENDER VARCHAR(5) NOT NULL,
   AGE  VARCHAR(5)              NOT NULL,
   PRIMARY KEY (USER_ID)
);

--//@UNDO

DROP TABLE USER;