CREATE TABLE QUESTION(
   ID INT   NOT NULL AUTO_INCREMENT,
   TITLE   VARCHAR (100)              NOT NULL,
   DESCRIPTION VARCHAR (1000)     NOT NULL,
   CREATED_AT DATETIME     NOT NULL,
   USER_ID  INT,
   PRIMARY KEY (ID)
);

--//@UNDO

DROP TABLE QUESTION;