ALTER TABLE USER CHANGE COLUMN AGE AGE_RANGE INT(11) NOT NULL  ,
    ADD COLUMN PRIVACY INT(1) NOT NULL DEFAULT 0,
    ADD COLUMN CREATED_AT DATETIME NOT NULL ;

--//@UNDO

ALTER TABLE USER CHANGE COLUMN AGE_RANGE AGE INT(11) NOT NULL  ,
    DROP COLUMN PRIVACY ,
    DROP COLUMN CREATED_AT  ;