CREATE TABLE QUESTION1(
   ID INT   NOT NULL AUTO_INCREMENT,
   TITLE   VARCHAR (100)              NOT NULL,
   DESCRIPTION VARCHAR (500)     NOT NULL,
   DATE VARCHAR (10)     NOT NULL,
   TIME VARCHAR (20)              NOT NULL,
   USER  VARCHAR (20) ,
   PRIMARY KEY (ID)
);

--//@UNDO

DROP TABLE QUESTION1;