CREATE  TABLE `forum`.`USER_PRIVILEGE` (
  `ID` INT NOT NULL AUTO_INCREMENT ,
  `USER_ID` INT NOT NULL ,
  `PRIVILEGE` INT NOT NULL DEFAULT 4 ,
  PRIMARY KEY (`ID`) ,
  INDEX `PRIVILEGE_USER_ID_idx` (`USER_ID` ASC) ,
  CONSTRAINT `PRIVILEGE_USER_ID_FK`
    FOREIGN KEY (`USER_ID` )
    REFERENCES `forum`.`USER` (`ID` )
    ON DELETE RESTRICT
    ON UPDATE RESTRICT);

--//@UNDO

drop table `forum`.`USER_PRIVILEGE`;