CREATE TABLE QUESTION_TAG(
QUESTION_ID INT NOT NULL,
TAG_ID INT NOT NULL,
PRIMARY KEY (TAG_ID,QUESTION_ID),
CONSTRAINT FOREIGN KEY (QUESTION_ID) REFERENCES QUESTION(ID)ON DELETE RESTRICT ON UPDATE RESTRICT,
CONSTRAINT FOREIGN KEY (TAG_ID) REFERENCES TAG(ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

--//@UNDO

DROP TABLE QUESTION_TAG;