CREATE TABLE ADVICE(
   ID INT   NOT NULL AUTO_INCREMENT,
   DESCRIPTION  VARCHAR (2000)              NOT NULL,
   QUESTION_ID  INT        NOT NULL,
   CREATED_AT DATETIME     NOT NULL,
   USER_ID  INT     NOT NULL,
   PRIMARY KEY (ID)
);

--//@UNDO

DROP TABLE ADVICE;